### ISSUE TITLE
what are the differences between your softer-NMS detectron version and original detectron?

### ISSUE THREAD

**Issue by gittigxuy** [yihui-he/softer-NMS#3] opened 2018-09-27 05:43 UTC
several days ago,I run another repo:https://github.com/LeonJWH/detectron-cascade-rcnn-exp
this repo just upload 2 folder,config and detectron,it is clearly to let me know the structure.but how could I use your repo?where could I find the implement of softer-NMS[I think maybe in detectron folder].So,I just change the detectron folder name to detectron_nms,and when I want to train dataset,I just change the yaml file,is that true?Thanks.

**Comment by gittigxuy** [comment] 2018-09-27 05:54
Furthermore,if I want to use mask rcnn to train the coco dataset,how could I change the fast_rcnn_R-50-FPN_2x_our.yaml file?just change the model file?or another code?Thanks

**Comment by yihui-he** [comment] 2018-09-27 10:14
Duplicate of #2

**Closed by yihui-he** 2018-09-27 10:14 UTC
